version: '3.1'

services:

  db:
    image: mongo:4
    restart: always
    volumes: 
        - ./docker-data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  api:
    image: learn-alphabet-api
    build: .
    restart: on-failure
    depends_on: 
        - db
    volumes:
        - ./:/usr/src/app:cached
    ports:
      - ${PORT}:${PORT}
    environment:
        MONGO_HOST: ${MONGO_HOST}
        MONGO_PORT: ${MONGO_PORT}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
        PORT: ${PORT}
